// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZKMiw8IHLA9x_tFxRWpaxhcIYE_hlRfU',
    appId: '1:578272155043:web:f0f758c4aec95fdf273616',
    messagingSenderId: '578272155043',
    projectId: 'kinohub',
    authDomain: 'kinohub-8ba62.firebaseapp.com',
    storageBucket: 'kinohub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbcfxmx3Mz-GeNIITceD7_ekvJBCoAM0',
    appId: '1:578272155043:android:024478eb6d4100c6273616',
    messagingSenderId: '578272155043',
    projectId: 'kinohub',
    storageBucket: 'kinohub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWARVwunSv08vzg1eubVLYrtHRNfb3FA',
    appId: '1:578272155043:ios:f72fa8051fc77b24273616',
    messagingSenderId: '578272155043',
    projectId: 'kinohub',
    storageBucket: 'kinohub.appspot.com',
    iosBundleId: 'com.KinoHUB.kinohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQWARVwunSv08vzg1eubVLYrtHRNfb3FA',
    appId: '1:578272155043:ios:152754157d91dc7b273616',
    messagingSenderId: '578272155043',
    projectId: 'kinohub',
    storageBucket: 'kinohub.appspot.com',
    iosBundleId: 'com.KinoHUB.kinohub.RunnerTests',
  );
}
